<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\pong_echec\pong_echec.csproj" />
    <ProjectReference Include="..\pong_serveur\pong_serveur.csproj" />
  </ItemGroup>
  
</Project>